require "visa_net_uy/encoder"
require "visa_net_uy/cipher"
require "visa_net_uy/plug_in"
require "visa_net_uy/signer"
require "visa_net_uy/version"
require "visa_net_uy/xmler"

module VisaNetUy

  VALID_FIELDS = [
    'acquirerId',
    'commerceId',
    'purchaseCurrencyCode',
    'purchaseAmount',
    'purchaseOperationNumber',
    'billingAddress',
    'billingCity',
    'billingState',
    'billingCountry',
    'billingZIP',
    'billingPhone',
    'billingEMail',
    'billingFirstName',
    'billingLastName',
    'language',
    'commerceMallId',
    'terminalCode',
    'tipAmount',
    'HTTPSessionId',
    'shippingAddress',
    'shippingCity',
    'shippingState',
    'shippingCountry',
    'shippingZIP',
    'shippingPhone',
    'shippingEMail',
    'shippingFirstName',
    'shippingLastName',
    'reserved1',
    'reserved2',
    'reserved3',
    'reserved4',
    'reserved5',
    'reserved6',
    'reserved7',
    'reserved8',
    'reserved9',
    'reserved10',
    'reserved11',
    'reserved12',
    'reserved13',
    'reserved14',
    'reserved15',
    'reserved16',
    'reserved17',
    'reserved18',
    'reserved19',
    'reserved20',
    'reserved21',
    'reserved22',
    'reserved23',
    'reserved24',
    'reserved25',
    'reserved26',
    'reserved27',
    'reserved28',
    'reserved29',
    'reserved30',
    'reserved31',
    'reserved32',
    'reserved33',
    'reserved34',
    'reserved35',
    'reserved36',
    'reserved37',
    'reserved38',
    'reserved39',
    'reserved40'
  ]

end
